from __future__ import annotations

"""Layout PPD MC/OR — colunas da planilha municipal de referência."""

# Índices 0-based (coluna G = 6)
COL_ROW_TYPE = 6
COL_ITEM = 7
COL_SOURCE_CODE = 8
COL_DESCRIPTION = 9
COL_UNIT = 10
COL_QUANTITY = 11
COL_UNIT_COST_COMD = 12
COL_UNIT_PRICE_BDI_COMD = 13
COL_TOTAL_COMD = 14
COL_UNIT_COST_SEMD = 15
COL_UNIT_PRICE_BDI_SEMD = 16
COL_TOTAL_SEMD = 17
COL_BDI = 12

DATA_START_ROW = 19
HEADER_LABELS = ("PROJETO", "OBJETO", "LOCAL", "ORÇAMENTO", "ORCAMENTO", "BASE DE PREÇO UTILIZADA")

ROW_TYPE_ETAPA = "ETAPA"
ROW_TYPE_SUB_ETAPA = "SUB-ETAPA"
ROW_TYPE_SERVICO = "S"
ROW_TYPE_MEMORIA = "MEMORIA"

PPD_TEMPLATE_ID = "PPD_MC_OR"
