version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: ia_server_santos_db
    restart: always

    environment:
      POSTGRES_USER: ia_user
      POSTGRES_PASSWORD: ia_password
      POSTGRES_DB: ia_server_santos

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ia_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
